apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: domain-ingress-certs
  namespace: istio-system
spec:
  acme:
    config:
    - dns01:
        provider: clouddns
      domains:
      - '*.gke-istio.arctic-lab.mattandes.com'
  commonName: '*.gke-istio.arctic-lab.mattandes.com'
  dnsNames:
  - '*.gke-istio.arctic-lab.mattandes.com'
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-staging
  secretName: istio-ingressgateway-certs