---
- hosts:
    - jenkins
  vars_files:
    - vars/main.yml
  roles:
    - role: geerlingguy.java
    - role: geerlingguy.jenkins
    - role: mattandes.jenkins_casc
      tags:
        - jenkins-casc
    - role: geerlingguy.git